### ISSUE TITLE
Bug - GUI Scaling Ruins the Main Menu Entirely

### ISSUE THREAD

**Issue by Tylerun** [BisectStudios/ProletariaExpertIssues#1]
Do not know if this is fixable from a mod standpoint but its super annoying. Larger and smaller screens will have the auto gui mess with the entire aesthetic of the main menu.

<img width="960" alt="gui" src="https://user-images.githubusercontent.com/29389193/166178003-b5326d90-2460-41d9-96cf-eb2ceb53eda2.png">

**Comment by Quarris** [comment]
This is weird, did you get this by default when you first launched the pack to did you change the gui scale to get this effect?

**Comment by Tylerun** [comment]
By default. The image seems to be in a ratio that breaks any monitor over 1080p but thats just an observation
