### ISSUE TITLE
Bug - The Natural Beginnings Must be claimed via claim all 

### ISSUE THREAD

**Issue by Tylerun** [BisectStudios/ProletariaExpertIssues#2]
Quest 1: The Natural Beginnings must be claimed via the claim all button. Otherwise the stages do not prompt properly. 

Workaround use claim all. 
<img width="733" alt="quest1 autoclaim" src="https://user-images.githubusercontent.com/29389193/166180247-3c0a3d69-6d73-4df2-afd4-30872b57b530.png">

**Comment by Quarris** [comment]
Can you describe this more? These 2 rewards are set to auto claim.

**Comment by Quarris** [comment]
Potential bug with the mod. We have reported this and are awaiting response.

**Comment by Tylerun** [comment]
For describing it seems that after completing the first quest those two quests depicted above did not claim on their own. I had to use the claim all button to force them to claim as i could not see them under rewards.

**Comment by Quarris** [comment]
We have redone the commands from quests to advancements which such solve most of these issues. This is a bug with FTB Quests
