### ISSUE TITLE
menu jittering/blurry tree

### ISSUE THREAD

**Issue by Warbringer12** [BisectStudios/ProletariaExpertIssues#4]
the background image jitters when in motion causing some weird tessellation in the background to happen.

please also fix this
![image](https://user-images.githubusercontent.com/44590540/166182010-d2debe55-7dd3-4fbb-aa3a-9744dc2d07d2.png)
as trees shouldn't be blurry up close to a person

**Comment by Tylerun** [comment]
Yeah left side of the artwork it shows that tree as a foreground item and blurs it.

**Comment by ThePlagueDoctor** [comment]
Yeah, it is blurred as all hell.

**Comment by Quarris** [comment]
> the background image jitters when in motion causing some weird tessellation in the background to happen.
> 
> please also fix this ![image](https://user-images.githubusercontent.com/44590540/166182010-d2debe55-7dd3-4fbb-aa3a-9744dc2d07d2.png) as trees shouldn't be blurry up close to a person

Can you defined jittery? Are you able to provide short clip of this as I cannot reproduce this.

Blurred tree is intentional. Yes things up close can be blurred.
