### ISSUE TITLE
Bug - Game Stage Bypass Via Vanilla Obsidian Monument

### ISSUE THREAD

**Issue by Tylerun** [BisectStudios/ProletariaExpertIssues#5]
Some stage restrictions can be bypassed via finding obsidian monuments

<img width="712" alt="stage" src="https://user-images.githubusercontent.com/29389193/166182493-d288f7f8-2cd9-4718-b10f-b040960025e8.png">

**Comment by Tylerun** [comment]
Received a flint and steel as well as iron nuggets. Bypassing stage 1 while in stage 1

**Comment by MasterSloth1** [comment]
Please DO NOT USE the loot from these loot chests the destroyed nether portals are NOT ment to be spawning, using the loot inside will break your progression

**Comment by Quarris** [comment]
Wait, what world type are you using? It should default to Terraforged terrain type and ruined portals do appear to be disabled as intended.

Edit: Is this on a server?

**Comment by Tylerun** [comment]
type is default on a server as no server existed for my friends and I to play on. No documentation requesting type to be set to "Terraforged" anywhere on the curse so if thats the problem thats my bad. We will adjust and report back.

**Comment by Tylerun** [comment]
<img width="1167" alt="newgeneration" src="https://user-images.githubusercontent.com/29389193/166344155-e640bf1a-53cc-43cc-9b03-8008197b1aa6.png">
<img width="332" alt="terra" src="https://user-images.githubusercontent.com/29389193/166344156-f41da4d5-7857-485c-9add-546d4ee20ca9.png">

Newly generated chunks are still showing these monuments with gold bypasses

**Comment by Tylerun** [comment]
Go ahead and close this. Need to add documentation to the site

**Comment by Quarris** [comment]
Server files are now released on CF
