### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Cactusstudent** [BisectStudios/ProletariaExpertIssues#6]
1. I'm a Chinese player of this Modpack. When I was playing this Modpack, I noticed that the descriptions of Quests in many chapters have the word BEIB. I'm not sure about this word. So, could you tell me what's the meaning of the word, Thanks. 
The modpack is great, I'll share it to my friends.
2. The textures of Livingwood - Mana Input Port & Livingrock - Mana Input Port are too similar. Can you change the textures.
3. Thank you for watching it.
(Here is the Screenshot about the Livingwood - Mana Input Port & Livingrock - Mana Input Port)
![image](https://user-images.githubusercontent.com/97865546/170291269-82a36327-e39e-4283-92e6-6eb940860c59.png)

**Comment by Quarris** [comment]
Hey, the BEIB is an old name for the guide book, which is now called PIP (Proletaria Information Pampthlet). Where is the BEIB mentioned?

The textures are specific because of the structures, they are different enough and we will not be changing the textures, sorry

**Comment by Cactusstudent** [comment]
Oh, I see. Thank you for telling me

**Comment by Cactusstudent** [comment]
The BEIB is in the Main Questline  02 - Technical Beginnings （My Modpack version is 1.1.1）

**Comment by Cactusstudent** [comment]
> The BEIB is in the Main Questline 02 - Technical Beginnings （My Modpack version is 1.1.1）

It's in 05 - The End ? too.

**Comment by Quarris** [comment]
Thank you for the quest book comments! It has been fixed in development and will be released in the next patch
