### ISSUE TITLE
Botanist's Smelter & Blaster use Mana while Idle

### ISSUE THREAD

**Issue by MCMan6482** [BisectStudios/ProletariaExpertIssues#7]
Really enjoying the pack so far but think I ran into an issue.

The Botanist's Smelter & Blaster use botania mana whenever an ore chunk is put into the Item input.

To replicate the issue:
- Build the Botanist's Smelter multiblock as shown in the PIP
- Supply Mana to the Mana Input Port
- Put copper chunks into the Item Input Port
- Observe mana leaving the Mana Input Port (roughly 1 mana unit/tick)

The issue persists when create rotation is applied but stops once rotational power is taken away.
Let me know if you need anymore details or if the issue can't be replicated.

Right now this is a huge roadblock as generating mana is still slow in this stage of the game and a ton of metal is needed. 
Also of note, alloying recipes don't seem to have the same issue

**Comment by MasterSloth1** [comment]
this should be fixed in the latest version of the modpack
