### ISSUE TITLE
About The Quest

### ISSUE THREAD

**Issue by Cactusstudent** [BisectStudios/ProletariaExpertIssues#8]
Hey, it's me. Yesterday, a player found me. He said the quest had something wrong. He said _The quest let me to go to the `Shop/exotic item` to get the things in Atum, but I didn't found the chapter._ In the end, he open the `ftb_editng_mode` and found you set the `always_invisible:true`. That made us can not see this chapter at all!!!!
So I hope you can fix this bug in next version.(My modpack version is 1.1.1)
THANKS A LOT!!!

**Comment by MasterSloth1** [comment]
this should be fixed in V1.1.4 of the modpack
